import pygame
import sys 
pygame.init()

#---CONSTANTES DE CONFIGURACIÓN DE PANTALLA---
ANCHO, ALTO=800, 600 #CONSTANTES DE RESOLUCIÓN 
pantalla=pygame.display.set_mode((ANCHO, ALTO)) #VARIABLE LLAMADA PANTALLA, DETERMINADA POR LA RESOLUCIÓN (EN PÍXELES) ESTABLECIDA CON LAS ANTERIORES VARIABLES
pygame.display.set_caption('test') #DETERMINA EL NOMBRE QUE TENDRÁ LA VENTANA (PARTE SUPERIOR IZQUIERDA)
clock=pygame.time.Clock() #ESTA FUNCIÓN MÁS ADELANTE NOS AYUDARÁ A LIMITAR LOS FPS DE NUESTA VENTANA, DE NO USARLO, LA VENTANA CORRERÁ A UNOS FPS SIN LÍMITE, ESTRESANDO SIN SENTIDO LA CPU

#---COLORES A UTILIZAR--- (NOTAR QUE SON DETERMINADOS POR VALORES RGB, DESDE 0 HASTA 255)
BLANCO=(255,255,255) #R, G , B AL MÁXIMO, FORMAN EL BLANCO
AZUL=(0,0,255) #B AL MÁXIMO, AZUL PURO

#---FUENTES---
fuente=pygame.font.SysFont(None, 40) #CREA UN OBJETO FUENTE DE TAMAÑO 40 USANDO LA FUENTE ESTÁNDAR DEL SISTEMA (MÁS ADELANTE LA UTILIZAREMOS PARA TEXTO)

#---BUCLE PRINCIPAL---
#COMO QUEREMOS QUE LA VENTANA PERMANEZCA ABIERTA DURANTE LA DURACIÓN DEL JUEGO, SE DEBE ESTABLECER UN BUCLE
ejecutando=True #LO DEFINIMOS COMO VARIABLE PARA PODER CAMBIAR SU VALOR CUANDO SEA NECESARIO

while ejecutando:
    for evento in pygame.event.get(): #ESTA FUNCIÓN SE USA DENTRO DEL BUCLE PRINCIPAL DEL JUEGO, PARA REVISAR SI EL USUARIO HIZO ALGO
        if evento.type==pygame.QUIT:
            ejecutando=False #AL OCURRIR EL EVENTO "QUIT" QUE ES LA INSTRUCCIÓN PARA CERRAR EL PROGRAMA, LA VARIABLE SE REDEFINE PARA QUE EL BUCLE PRINCIPAL SE CORTE

    pantalla.fill(BLANCO) #AÑADE UN FONDO BLANCO A NUESTRA VARIABLE LLAMADA PANTALLA
    texto=fuente.render("TESTING", True, AZUL) #CREA UNA SUPERFICIE DE PYGAME (Surface) QUE CONTIENE EL TEXTO "TESTING"; True SIGNIFICA QUE SE APLICARÁ ANTIALIASING PARA QUE EL TEXTO TENGA SUAVIZADO, AZUL ES LA VARIABLE DE COLOR QUE DEFINIMOS ANTES, QUE DETERMINA EL COLOR DEL TEXTO
    pantalla.blit(texto, (50,50)) #EN LA LÍNEA DE ARRIBA SOLAMENTE CREAMOS EL OBJETO TEXTO Y SE GUARDÓ EN LA MEMORIA, CON ESTA LÍNEA SE DIBUJA EN PANTALLA. EL PARÁMETRO (50,50) SON SUS COORDENADAS

    pygame.display.flip() #ACTUALIZA TODA LA PANTALLA Y AÑADE LO QUE DIBUJAMOS (TEXTO, IMÁGENES, FORMA, ETC) EN ESTE CASO SE AÑADE EL TEXTO QUE DEFINIMOS ANTERIORMENTE
    clock.tick(60) #LÍMITA EL FRAMERATE A 60FPS, PARA EVITAR QUE EL PROGRAMA SOBREEXIJA AL SISTEMA

pygame.quit() #SE EJECUTA ÚNICAMENTE AL SALIR DEL BUCLE DE EJECUCIÓN DEL PROGRAMA, SE ENCARGA DE CERRAR  CORRECTAMENTE CADA MÓDULO DE PYGAME
sys.exit() #FUNCIONA IGUAL QUE EL COMANDO ANTERIOR, PERO EN ESTE CASO SALE COMPLETAMENTE DEL PROGRAMA DE PYTHON, LUEGO DE HABER CERRADO PYGAME